//
// Created by theob on 07/04/2023.
//

#ifndef PROJET_APPLICATION_CHIFFREMENT_DECHIFFREMENT_CESAR_CODE_H
#define PROJET_APPLICATION_CHIFFREMENT_DECHIFFREMENT_CESAR_CODE_H

#endif //PROJET_APPLICATION_CHIFFREMENT_DECHIFFREMENT_CESAR_CODE_H

void chiffrementCodeCesar(void);
void dechiffrementCodeCesar(void);
