//
// Created by theob on 07/04/2023.
//

#ifndef PROJET_APPLICATION_CHIFFREMENT_DECHIFFREMENT_CODE_VIGENERE_H
#define PROJET_APPLICATION_CHIFFREMENT_DECHIFFREMENT_CODE_VIGENERE_H

#endif //PROJET_APPLICATION_CHIFFREMENT_DECHIFFREMENT_CODE_VIGENERE_H

void chiffrementCodeVigenere(void);
void dechiffrementCodeVigenere(void);
